// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../closure-templates/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJs', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri', 'soydata.VERY_UNSAFE'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.soy.data.SanitizedContentKind', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../work/a20150207/js/main.js', ['work.a20150207.main'], ['goog.array', 'goog.dom', 'goog.events', 'goog.events.EventType', 'work.template.a20150207.popup', 'work.widget.Gallery', 'work.widget.Popup']);
goog.addDependency('../../../work/house/js/detail/main.js', ['work.house.detail.main'], ['goog.dom', 'work.widget.Gallery']);
goog.addDependency('../../../work/template/a20150207/popup.soy.js', ['work.template.a20150207.popup'], ['soy']);
goog.addDependency('../../../work/tga3c/js/index/main.js', ['work.tga3c.index.main'], ['goog.dom', 'work.widget.Gallery']);
goog.addDependency('../../../work/tingyuansan/js/about/main.js', ['work.tingyuansan.about.main'], ['goog.dom', 'work.tingyuansan.Head']);
goog.addDependency('../../../work/tingyuansan/js/common/head.js', ['work.tingyuansan.Head'], ['goog.dom', 'goog.events', 'goog.events.EventType']);
goog.addDependency('../../../work/tingyuansan/js/contact/main.js', ['work.tingyuansan.contact.main'], ['goog.dom', 'work.tingyuansan.Head']);
goog.addDependency('../../../work/tingyuansan/js/index/main.js', ['work.tingyuansan.index.main'], ['goog.dom', 'work.tingyuansan.Head', 'work.widget.Gallery']);
goog.addDependency('../../../work/tingyuansan/js/message/main.js', ['work.tingyuansan.message.main'], ['goog.dom', 'work.tingyuansan.Head']);
goog.addDependency('../../../work/tingyuansan/js/product/main.js', ['work.tingyuansan.product.main'], ['goog.dom', 'work.tingyuansan.Head']);
goog.addDependency('../../../work/tingyuansan/js/work/main.js', ['work.tingyuansan.work.main'], ['goog.dom', 'work.tingyuansan.Head']);
goog.addDependency('../../../work/widget/carousel.js', ['work.widget.Carousel'], ['goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.events.EventType', 'goog.fx.dom', 'goog.fx.easing', 'goog.style']);
goog.addDependency('../../../work/widget/gallery.js', ['work.widget.Gallery'], ['goog.array', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.events.EventType', 'goog.fx.dom', 'goog.fx.easing', 'goog.style']);
goog.addDependency('../../../work/widget/popup.js', ['work.widget.Popup'], ['goog.dom', 'goog.events', 'goog.events.EventType']);
goog.addDependency('../../../work/widget/tabpane.js', ['work.widget.TabPane'], ['goog.array', 'goog.dom', 'goog.dom.classlist', 'goog.events', 'goog.events.EventType']);
goog.addDependency('../../../work/widget/topfixer.js', ['work.widget.TopFixer'], ['goog.dom', 'goog.events', 'goog.events.EventType']);
